name: "Build"
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.0

      - name: Install Nix
        uses: cachix/install-nix-action@v23

      - name: Setup binary cache
        uses: cachix/cachix-action@v12
        with:
          name: stackrox
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build dev environment
        run: nix develop
