name: "Build"
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Free disk space
        # https://github.com/actions/virtual-environments/issues/709
        run: |
          echo "========= Original CI disk space"
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "========= After clean up CI disk space"
          df -h

      - name: Check out repository
        uses: actions/checkout@v4.2.0

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
            auto-optimise-store = true

      - name: Setup binary cache
        uses: cachix/cachix-action@v15
        with:
          name: stackrox
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build dev environment
        run: nix develop --fallback
